#!/usr/bin/env python3
"""Generate the private prototype paper collection from the curated Zotero snapshot."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "_data" / "zotero_snapshot.json"
PAPERS = ROOT / "_papers"
CATALOG = ROOT / "_data" / "catalog.json"
REVIEWED = "2026-08-23"

# key, category, tier, evidence type, context, sample, inclusion reason,
# main finding, limitations, NEXUS implication, score tuple, review basis, topics
A = [
("QYPFRUBZ","Reviews & Meta-Analyses","Core","Meta-analysis","School and higher-education service-learning programs","62 studies; 11,837 students","Provides the broadest outcome synthesis in the set and tests design practices associated with stronger results.","Compared with controls, service-learning showed significant gains across self, school/learning attitudes, civic engagement, social skills, and academic performance; curriculum links, student voice, community involvement, and reflection were associated with better outcomes.","Programs and measures were heterogeneous; reporting was incomplete; most studies were non-randomized, so moderator findings should not be read causally.","Treat reflection, community involvement, curriculum integration, and learner voice as design conditions to document, not decorative additions.",(3,3,2,2,1),"Full-text review",["meta-analysis","student outcomes","reflection","program design"]),
("P6GXDAN3","Reviews & Meta-Analyses","Core","Meta-analysis","Business and non-business service-learning","Quantitative empirical studies meeting four inclusion criteria","Separates social, personal, and cognitive outcomes and examines variation in service-learning design.","Average effects were positive across expected learning outcomes; discussion-based reflection appeared more supportive of understanding social issues than written reflection alone in the available comparisons.","The business-study subset was small, designs varied, and moderator analyses were constrained by the number and reporting quality of studies.","Use multiple outcome domains and preserve dialogic reflection when programs target social understanding.",(3,3,2,2,1),"Full-text review",["meta-analysis","cognitive outcomes","social outcomes","reflection"]),
("XSIUCHQY","Reviews & Meta-Analyses","Core","Systematic literature review","Service-learning across higher-education disciplines","133 studies selected for full-text review","Maps implementation, frameworks, disciplinary adoption, limitations, and stakeholder outcomes across higher education.","Service-learning was used across many disciplines and delivery modes, with recurring benefits for students and other stakeholders but uneven, subject-specific frameworks and implementation challenges.","The review is broad, but the appraisal of primary-study quality is less explicit than its search and classification process; conclusions inherit heterogeneity in the source literature.","Use the review as a landscape map and taxonomy source, then consult stronger primary evidence for specific outcome claims.",(3,2,2,2,1),"Full-text review",["systematic review","higher education","implementation","frameworks"]),
("PHWJCUJM","Reviews & Meta-Analyses","Recommended","Systematic literature review","Entrepreneurship education","Published experiential-learning studies in entrepreneurship education","Connects experiential-learning activities to entrepreneurial education, skills, and intention.","The reviewed literature generally associated experiential approaches with entrepreneurial intention, skills, and competencies, while showing that activities create different benefits and implementation demands.","The review is discipline-specific, includes heterogeneous activities and outcomes, and cannot establish that experiential learning alone produced the reported changes.","Use as a disciplinary application map and as evidence that activity design should be matched to the competency sought.",(2,2,2,2,0),"Full-text review",["systematic review","entrepreneurship","competencies","experiential learning"]),
("QTPJZ764","Reviews & Meta-Analyses","Recommended","Review article","Medical education and community-engaged service-learning","Published medical service-learning programs and projects","Extends the evidence map into professional education where service, adult learning, and community engagement intersect.","The review argues that well-integrated service-learning can support professional development and adult-learning principles while creating channels for reciprocal learning with communities.","The review is bounded to medical education and offers less transparent quality appraisal than the meta-analyses; program descriptions are heterogeneous.","Use it to identify design patterns for professional programs, not as a field-wide effect estimate.",(2,2,1,2,1),"Full-text review",["review","medical education","professional learning","community"]),
("95IXXXC4","Foundations & Theory","Foundational","Conceptual implementation framework","Higher-education institutions","Conceptual article; no empirical sample","Introduces the CAPSL approach and remains a central institutional framing for implementing service-learning.","The article organizes implementation around institutional constituencies and coordinated activities rather than treating service-learning as an isolated course technique.","No indexed full text was available for this prototype, and the framework predates much contemporary critical and equity-focused scholarship.","Use CAPSL as an institutional systems map, then update it with explicit power, reciprocity, access, and community-governance criteria.",(3,1,2,2,1),"Abstract/metadata review",["CAPSL","implementation","institutionalization","framework"]),
("F5AIPR73","Foundations & Theory","Core","Institutional survey study","Higher-education institutions using service-learning","Institutional respondents applying the CAPSL matrix","Empirically examines how service-learning becomes embedded across institutional, faculty, student, and community constituencies.","Planning and awareness were more developed than evaluation and research; institutionalization varied by constituency and was associated with actionable organizational conditions.","The authors describe the study as preliminary; ratings were self-reported, the instrument left achievement open to respondent interpretation, and causal direction is unresolved.","Track institutionalization across all four constituencies and invest early in evaluation, research, and community-facing infrastructure.",(3,2,2,2,1),"Full-text review",["institutionalization","CAPSL","higher education","evaluation"]),
("UXQSQC56","Foundations & Theory","Foundational","Conceptual framework with case application","Marketing education","One consumer-behavior course case plus design guidance","Makes the bridge between Kolb's experiential cycle and concrete service-learning course design explicit.","The framework links planning, implementation, reflection, and evaluation to experiential learning and illustrates how those elements can be applied in marketing courses.","The empirical basis is a single disciplinary case and the article predates later critiques of learning-style simplification and uncritical service relationships.","Use the cycle as a sequencing heuristic while avoiding claims that learners have fixed styles and adding reciprocal community co-design.",(3,1,2,2,0),"Full-text review",["Kolb","course design","marketing","experiential cycle"]),
("WTAK83RD","Foundations & Theory","Recommended","Qualitative case study","Australian higher education and community service placement","36 student questionnaire respondents plus reflective material","Clarifies how community service-learning differs from volunteering or generic experiential learning through curricular and community integration.","Students generally perceived the experience as relevant and beneficial for professional skill practice, personal development, and contribution to community welfare.","A small, single case relies heavily on participant perceptions; positive student experience does not demonstrate durable learning or community impact.","Preserve the distinctions among placement, volunteering, experiential learning, and reciprocal service-learning in NEXUS definitions.",(3,2,1,1,1),"Full-text review",["definitions","Australia","community service-learning","case study"]),
("5NQ259B5","Foundations & Theory","Emerging","Analytical narrative review","Higher education","Narrative survey of existing literature","Frames service-learning as a potentially transformative civic pedagogy and identifies tensions in higher education's public mission.","The review presents service-learning as a community-engagement approach that can connect academic goals with cultural competence, inclusion, and public purpose.","Search, selection, and quality-appraisal procedures are insufficiently reproducible, and some claims are broader than the evidence described.","Retain as a critical framing prompt, but do not use it alone to support effectiveness claims.",(3,1,1,1,1),"Full-text review",["transformative learning","critical pedagogy","public good","narrative review"]),
("CS3PP8PR","Design & Reflection","Recommended","Action-research alignment study","Online graduate library and information studies course","Course reflections collected across five years","Shows how constructive alignment can reveal whether service-learning assessments actually evidence intended outcomes.","Reflection evidence aligned unevenly with intended learning outcomes and prompted revision of outcomes and assessment design.","Students self-selected community partners, groups were uneven, the sample was small, and the single-course action-research design limits transferability.","Build an explicit chain from learning outcome to activity, reflection prompt, evidence, and scoring rule before a course launches.",(3,2,1,2,0),"Full-text review",["assessment","constructive alignment","reflection","action research"]),
("UP7S8GJE","Design & Reflection","Recommended","Qualitative case study","Extracurricular service-learning in Korean higher education","In-depth interviews with participating students","Identifies concrete experiences that appear to deepen learning rather than treating participation itself as the mechanism.","Seven experiences supported learning: addressing recipient-defined needs, student design, real-world problem solving, diverse collaboration, responsibility, managing discomfort, and reflection on interests and abilities.","Voluntary participation creates selection effects; the single Korean program and retrospective interviews limit generalization and causal claims.","Design for responsibility, discomfort processing, authentic need, collaboration, and transfer of reflection beyond the immediate project.",(3,2,2,2,0),"Full-text review",["learning process","student experience","Korea","reflection"]),
("RESBVRRZ","Design & Reflection","Core","Structural equation modeling study","Mandatory university service-learning in Hong Kong","More than 2,000 matched student responses across 132 subjects","Offers unusually large process-level evidence connecting experience, motivation, and cognitive learning.","Model estimates support relationships among learning experience, expectancy-value motivation, and cognitive learning outcomes across a large multi-course sample.","Response attrition and self-report measures remain important; structural equation modeling supports a theoretical association pattern, not causal proof.","Measure the motivational pathway and quality of experience, not only end-of-course satisfaction or outcome scores.",(3,3,2,2,0),"Full-text review",["motivation","structural equation modeling","cognitive learning","Hong Kong"]),
("4XJC2CNR","Design & Reflection","Emerging","Qualitative single-case study","Clinical education in South Africa","Six purposively sampled students","Provides a focused account of debriefing as the reflective bridge between experience and critical thinking.","Participants described debriefing as supporting analysis, decision-making, and critical thinking in clinical practice, while also identifying implementation challenges.","Six participants from one institution, no comparison condition, and self-reported experience preclude effectiveness or generalizability claims.","Treat facilitated debriefing as a design hypothesis worth testing with direct critical-thinking measures and broader samples.",(2,1,1,2,1),"Full-text review",["debriefing","critical thinking","clinical education","South Africa"]),
("S75XGURH","Design & Reflection","Recommended","Qualitative content analysis","Service-learning during the 2022 FIFA World Cup in Qatar","Undergraduate end-of-semester reflection papers","Offers a concrete, assessable reflection structure using Objective, Reflective, Interpretive, and Decisional prompts.","ORID-structured reflections moved beyond event description toward emotional, cognitive, prospective, and solution-oriented interpretation.","The evidence comes from one distinctive event context, uses submitted reflections, and lacks an unstructured or alternative-prompt comparison.","Pilot ORID as a common reflection scaffold, while evaluating whether depth reflects learning rather than writing compliance.",(3,2,1,2,0),"Full-text review",["ORID","reflection","assessment","Qatar"]),
("SJ3LTXLA","Reciprocity & Justice","Core","Participatory qualitative study using photovoice","International service-learning partnership in Uganda","Hearing and deaf host-community participant-researchers","Centers host-community knowledge and exposes relationship benefits and tensions often omitted from student-focused research.","Participants emphasized friendship, educational relationships, and relationships supporting social change, while also surfacing complex questions about power and the nature of international partnerships.","Findings are context-specific; photovoice participation and publication choices shape which community perspectives are represented.","Require host-community interpretation of outcomes and treat relationships, power, accessibility, and co-authorship as evidence, not background context.",(3,2,2,1,2),"Full-text review",["photovoice","Uganda","host community","international service-learning"]),
("GZR4UGG4","Reciprocity & Justice","Recommended","Qualitative questionnaire study","Compulsory community-engagement module at the University of Pretoria","36 community-partner responses","Directly examines community partners as co-educators rather than service recipients.","Partners described expertise they contribute to student learning and the potential for long-term reciprocal relationships with students and the university.","This appraisal is abstract-level; self-perception, one module, and 36 responses constrain conclusions about actual reciprocity or community outcomes.","Formalize community partners' educational authority, feedback rights, continuity, and role in defining successful outcomes.",(3,2,1,1,1),"Abstract/metadata review",["community partners","co-education","reciprocity","South Africa"]),
("UMP5I3HM","Reciprocity & Justice","Recommended","Quantitative and qualitative course study","Ten service-learning courses at one urban U.S. university","125 undergraduate students","Tests relationships as a plausible mechanism connecting service-learning participation to civic orientation.","Positive relationships with professors, community partners, and peer mentors were associated with stronger reported intentions for future civic engagement.","The single-site sample was small, service experiences varied, associations are noncausal, and the study did not establish benefits for community partners.","Measure relationship quality across students, faculty, peers, and partners, but pair student attitudes with community-defined outcome evidence.",(3,2,1,1,1),"Full-text review",["relationships","civic engagement","mentoring","community partners"]),
("TNF6HBR4","Reciprocity & Justice","Core","Mixed-methods comparative course study","Three psychology classes at a Southern California university","125 undergraduates, predominantly students of color","Provides empirical evidence on combining service-learning with critical curriculum rather than assuming service automatically produces justice orientations.","Critical service-learning and critical-curriculum groups showed stronger civic orientations and lower social-dominance orientations than a traditional class; within-person results suggested some change over time.","Classes were not randomized, instructors and course designs may differ, and outcomes are attitudinal rather than evidence of community-level change.","Pair service with explicit critical curriculum and measure justice orientations, while avoiding claims that service alone transforms power relations.",(3,2,2,1,2),"Full-text review",["critical service-learning","social justice","civic engagement","mixed methods"]),
("FM2QLXHD","Reciprocity & Justice","Recommended","Conceptual essay and research agenda","Postsecondary service-learning access","No empirical sample","Makes access to service-learning itself an equity question, especially for students facing institutional and resource barriers.","The article identifies recruitment, navigation, time, and institutional processes as possible barriers and calls for qualitative inquiry centered on underrepresented students' experiences.","It proposes lines of inquiry rather than testing them; effectiveness and prevalence of the proposed barriers remain empirical questions.","Audit who can participate, who is recruited, hidden costs, scheduling, transport, and institutional navigation before calling a program inclusive.",(3,1,1,1,2),"Full-text review",["equity","access","underrepresented students","research agenda"]),
("PP8FA7GD","Outcomes & Institutional Practice","Recommended","Empirical effectiveness study","Higher-education service-learning","Study sample requires full-text confirmation","Adds an important counterweight to uniformly positive narratives by focusing on how effectiveness is defined and measured.","The record is retained because it explicitly questions simple effectiveness assumptions; the exact design and findings must be verified from full text before public use.","No indexed PDF or abstract was available in Zotero, so this prototype does not make a substantive outcome claim from the title alone.","Keep the paper as a methodological caution and block public promotion until the researcher completes full-text review.",(3,1,2,1,1),"Abstract/metadata review",["effectiveness","measurement","service-learning outcomes","caution"]),
("PRUTCBXM","Outcomes & Institutional Practice","Recommended","Test-retest comparative study","Undergraduate course-based service-learning","23 service-learning students and 107 comparison students","Uses multiple academic measures and addresses selection bias rather than relying only on satisfaction reports.","Service-learning did not improve final examination marks, but the study found more nuanced benefits on course-specific comprehension and reported civic, interpersonal, and practical development.","The service-learning group was small, assignment and self-report measures remain context-bound, and multiple tests raise error-rate concerns.","Use direct, outcome-specific measures and report null academic results alongside civic and practical gains.",(3,2,2,2,0),"Full-text review",["academic outcomes","civic responsibility","comparative study","measurement"]),
("A5XHRWTK","Outcomes & Institutional Practice","Recommended","Qualitative implementation study","Arts-based service-learning with Indigenous communities in Australia","Small sample of experienced educator-researchers","Connects partnership work to the organizational tactics needed to start and sustain service-learning.","The analysis supported four established implementation tactics and added institutional commitment as a fifth, while highlighting reliance on champions and unrecognized gift labor.","A small, expert, educator-researcher sample and arts/Indigenous context limit transfer; community evidence is present but organizational claims need broader testing.","Budget for institutional commitment, continuity, recognition, and labor instead of building programs around individual goodwill.",(3,2,1,1,2),"Full-text review",["sustainability","institutional commitment","Indigenous communities","arts"]),
("77Z7FAHP","Outcomes & Institutional Practice","Recommended","Applied case study","Cross-disciplinary higher education partnership in the United Arab Emirates","First-year bachelor students completing a public-sector heritage and tourism brief","Shows how an external educational partnership can turn curriculum requirements into a bounded learning-by-doing project with an authentic partner brief.","Students across disciplines researched, analyzed, evaluated, and produced materials for a public-sector partner; staff reported stronger motivation, personal development, and overall learning experience.","The case is descriptive, staff perceptions are prominent, outcome measures are not comparative, and the informal partnership may not transfer to differently governed institutions.","Use authentic partner-defined briefs and cross-disciplinary production, but add direct student and partner outcome measures before claiming effectiveness.",(2,2,1,2,1),"Full-text review",["educational partnership","United Arab Emirates","learning by doing","cross-disciplinary"]),
("BZC7V43D","Outcomes & Institutional Practice","Recommended","Conceptual model and recommendations","Adapted physical activity and kinesiology service-learning","No empirical sample","Integrates experiential learning with relational ethics and inclusion for programs involving people with impairments.","The article proposes empirically and theoretically informed questions and recommendations for designing, implementing, and evaluating programs around the needs of both university and community stakeholders.","The proposed model is conceptual and discipline-specific; its recommendations need empirical testing with participants with impairments as co-evaluators.","Build accessibility, relational ethics, and stakeholder-defined educational interests into program governance and evaluation from the start.",(3,1,2,1,1),"Full-text review",["inclusion","disability","relational ethics","kinesiology"]),
]


def year_of(date: str) -> str:
    match = re.search(r"(?:19|20)\d{2}", date or "")
    return match.group(0) if match else "n.d."


def authors_of(creators: list[dict]) -> list[str]:
    result = []
    for creator in creators:
        name = creator.get("name") or " ".join(
            part for part in (creator.get("firstName", ""), creator.get("lastName", "")) if part
        )
        if name:
            result.append(name)
    return result


def q(value) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    snapshot = {item["key"]: item["data"] for item in json.loads(SNAPSHOT.read_text())}
    PAPERS.mkdir(exist_ok=True)
    catalog = []
    for order, row in enumerate(A, start=1):
        (key, category, tier, evidence, context, sample, reason, finding,
         limitations, implication, scores, basis, topics) = row
        data = snapshot[key]
        authors = authors_of(data.get("creators", []))
        year = year_of(data.get("date", ""))
        doi = (data.get("DOI") or "").strip()
        record = {
            "order": order, "zotero_key": key, "title": data["title"],
            "authors": authors, "year": year,
            "journal": data.get("publicationTitle") or "Journal title requires verification",
            "doi": doi, "category": category, "tier": tier,
            "evidence_type": evidence, "context": context, "sample": sample,
            "inclusion_reason": reason, "main_finding": finding,
            "limitations": limitations, "nexus_implication": implication,
            "score_relevance": scores[0], "score_rigor": scores[1],
            "score_contribution": scores[2], "score_transferability": scores[3],
            "score_equity": scores[4], "score_total": sum(scores),
            "review_basis": basis, "reviewed_date": REVIEWED, "topics": topics,
        }
        catalog.append(record)
        front = ["---", "layout: paper"]
        for field in ("order","zotero_key","title","authors","year","journal","doi","category","tier",
                      "evidence_type","context","sample","inclusion_reason","score_relevance","score_rigor",
                      "score_contribution","score_transferability","score_equity","score_total","review_basis",
                      "reviewed_date","topics"):
            front.append(f"{field}: {q(record[field])}")
        front.append("---")
        body = f"""
## Why this paper is included

{reason}

## Evidence and main finding

**Design:** {evidence}. **Context:** {context}. **Sample:** {sample}.

{finding}

## Important limitations

{limitations}

## Implication for NEXUS

{implication}

## Appraisal note

This is a {basis.lower()} completed on {REVIEWED}. The score is an editorial aid under the [published NEXUS rubric]({{{{ '/methodology/' | relative_url }}}}); it is not a precise ranking or a substitute for independent scholarly review.
"""
        (PAPERS / f"{order:02d}-{key.lower()}.md").write_text("\n".join(front) + body, encoding="utf-8")
    CATALOG.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"generated {len(catalog)} paper appraisals")


if __name__ == "__main__":
    main()
